name: test

on: 
  pull_request:
    types: 
      - opened

jobs:
  curl_test:
    runs-on: ubuntu-latest 
    steps:
    - name: test
      run: |
        echo "hello world"
        echo ${{github.event.pull_request }}
        echo ${{github.event.action}}
        echo ${{github.event}}
